In [86]:
import os
import re
import matplotlib.pyplot as plt
import numpy as np
import string
import pandas as pd
import pyspark.sql.functions as F

from pyspark.sql.functions import udf
from pyspark.sql import SparkSession
from pyspark.sql.types import IntegerType, FloatType
from __future__ import print_function, unicode_literals, with_statement, absolute_import, generators, nested_scopes, division
from pyspark.sql.functions import mean, stddev
%matplotlib inline

In [8]:
# Local Spark
# spark session is now the entry point of spark program
# for line 8, can use local[n] for run spark locally with n cores
spark = SparkSession.builder \
    .master('local') \
    .appName('Spark Try') \
    .getOrCreate()

In [75]:
data = spark.read.json('/project/cmsc25025/beer_review/labeled.json').dropna()
data.show(5)

+----------+-----+-------+--------------------+------+-------+------+--------------------+---------+-----+-----+
|appearance|aroma|beer_id|           beer_name|brewer|overall|palate|              review|review_id|style|taste|
+----------+-----+-------+--------------------+------+-------+------+--------------------+---------+-----+-----+
|       4.0|  6.0|  45842|John Harvards Sim...|  3084|   13.0|   3.0|On tap at the Spr...|        0|   17|  6.0|
|       4.0|  6.0|  45842|John Harvards Sim...|  3084|   13.0|   4.0|On tap at the Joh...|        1|   17|  7.0|
|       4.0|  5.0|  95213|John Harvards Cri...|  3084|   14.0|   3.0|UPDATED: FEB 19, ...|        2|   33|  6.0|
|       2.0|  4.0|  65957|John Harvards Fan...|  3084|    8.0|   2.0|On tap the Spring...|        3|   33|  4.0|
|       5.0|  8.0|  41336|John Harvards Van...|  3084|   16.0|   4.0|Springfield, PA l...|        5|   58|  7.0|
+----------+-----+-------+--------------------+------+-------+------+--------------------+---------+-----+-----+
only showing top 5 rows

# Part 1: Data inspection
check the mean, median and standard deviation of the overall ratings for each beer and brewer. Do you think people have similar taste?

In [78]:
data.select('overall').describe().show()

+-------+------------------+
|summary|           overall|
+-------+------------------+
|  count|           2486348|
|   mean|13.198879641948754|
| stddev|3.3523514833201147|
|    min|               1.0|
|    max|              20.0|
+-------+------------------+

In [85]:
def find_median(values_list):
    try:
        median = np.median(values_list) #get the median of values in a list in each row
        return round(float(median),2)
    except Exception:
        return None #if there is anything wrong with the given values

median_finder = udf(find_median,FloatType())

In [97]:
df_a = data.groupBy('beer_name').agg({'overall': 'stddev'}).toPandas()
df_b = data.groupBy('beer_name').agg({'overall': 'mean'}).toPandas()
df_c = data.groupBy('beer_name').agg(F.collect_list('overall').alias('m')).withColumn("median",median_finder("m")).toPandas()
df_c = df_c.iloc[:,[0,2]].set_index('beer_name')

df_beer = df_a.set_index('beer_name').join(df_b.set_index('beer_name')).join(df_c).sort_values(by = 'stddev(overall)', ascending = False)
df_beer

,stddev(overall),avg(overall),median
beer_name,,,
Mountain Town Ultra Lite,12.727922,11.000000,11.0
Left Hand Bourbon Barrel Milk Stout,11.313708,10.000000,10.0
Four Peaks Barrel-Aged Blind Date Ale,11.313708,9.000000,9.0
Berliner Kindl Weisse Tropical,11.313708,12.000000,12.0
Lovejoys Folsom Prison Blueberry Porter,11.313708,10.000000,10.0
Samuel Adams Bitter,10.606602,12.500000,12.5
LCL Pils &#40;Draught&#41;,10.606602,12.500000,12.5
John S. Rhodell Cherry Dark Ale,10.606602,9.500000,9.5
Molson Carling Extreme,10.606602,10.500000,10.5
Wilkenny Roja,9.899495,10.000000,10.0
Cody Last Minute Vanilla Pumpkin Stout,9.899495,9.000000,9.0
Blind Man Pale Ale,9.899495,12.000000,12.0
Ranger Creek Re: Session IPA,9.899495,11.000000,11.0
Mountain Town French Country Ale,9.899495,13.000000,13.0
Bobcat Cafe Wee Heavy Scotch Ale,9.899495,9.000000,9.0
Owens Blueberry Ale,9.899495,10.000000,10.0
Harmon Stryker Stout,9.899495,8.000000,8.0
Sportz Beer,9.500000,5.750000,1.0
Abbeydale Wheat Beer,9.192388,10.500000,10.5
Napa Smith Hopaggedon Imperial IPA,9.192388,10.500000,10.5
Astoria Moonbeam Blue,9.192388,13.500000,13.5
Manns Light Ale,9.192388,11.500000,11.5
Pittsfield Brew Works Bees Knees Barley Wine,9.192388,11.500000,11.5
Weltons Xmas Old,9.192388,7.500000,7.5
Bitter End Chewbocka,9.192388,7.500000,7.5
McMenamins Seasonal Madness,9.192388,9.500000,9.5
Brew Brothers IPA,9.192388,8.500000,8.5
WF6 Birkwood Original,9.192388,7.500000,7.5
Redburn Twice Brewed IPA,9.192388,7.500000,7.5
Matt Private Mens Club Pilsner,9.073772,9.666667,6.0
...,...,...,...
Vintage Day Tripper Summer Ale,NaN,14.000000,14.0
Astoria Blueberry Lambic,NaN,12.000000,12.0
Trap Rock Belgian Rye Ale,NaN,14.000000,14.0
Budgens Our Kitchen Vintage Medium Sweet Cider,NaN,11.000000,11.0
Kelham Island Cool For Cats,NaN,13.000000,13.0
Wentworth American Pale Ale,NaN,14.000000,14.0
Odd Side Ales Banana Cream Pie Ale,NaN,13.000000,13.0
Odd Side Ales Hysteria,NaN,11.000000,11.0
Cropton Royal Union,NaN,13.000000,13.0
Chi Town Lake Shore Lager,NaN,8.000000,8.0
Barleys Casino Golden Honey,NaN,12.000000,12.0
Judge Baldwins Marzen-Octoberfest,NaN,15.000000,15.0
Tryst Citra Hop Trial,NaN,15.000000,15.0
Wormtown Wintah Ale,NaN,14.000000,14.0
Southern Tier Pale Rider,NaN,18.000000,18.0
Titanic Brewing 80 Schilling Scottish Ale,NaN,13.000000,13.0
Bibo Bock,NaN,12.000000,12.0
West Berkshire Copper Hop,NaN,16.000000,16.0
Flatlanders Scottish Ale,NaN,12.000000,12.0
"Capitol City Red, Wheat and Blue",NaN,11.000000,11.0
Castroper Wiesen,NaN,11.000000,11.0
Jarrow Westoe Netty Special,NaN,16.000000,16.0
Rogue Barrel Aged Imperial Red,NaN,13.000000,13.0
Gasthausbrauerei Sudhaus Dunkel,NaN,10.000000,10.0
Leeds Winter Spark,NaN,13.000000,13.0
San Juan Mt. Finlayson Ippa-Weizen,NaN,9.000000,9.0
Twin Ports Maibock,NaN,14.000000,14.0
Big Boss Lucky Bastard Porter,NaN,11.000000,11.0
South Street Sorghum Stout,NaN,10.000000,10.0
Harpers Amberfest,NaN,13.000000,13.0

In [99]:
df_d = data.groupBy('brewer').agg({'overall': 'stddev'}).toPandas()
df_e = data.groupBy('brewer').agg({'overall': 'mean'}).toPandas()

df_f = data.groupBy('brewer').agg(F.collect_list('overall').alias('m')).withColumn("median",median_finder("m")).toPandas()
df_f = df_f.iloc[:,[0,2]].set_index('brewer')

df_brewer = df_d.set_index('brewer').join(df_e.set_index('brewer')).join(df_f).sort_values(by = 'stddev(overall)', ascending = False)
df_brewer

        stddev(overall)  avg(overall)  median
brewer
5012           9.899495     13.000000    13.0
7132           9.192388      7.500000     7.5
5580           8.962886      9.666667     5.0
7373           8.906926     10.000000     9.0
3448           8.485281      8.000000     8.0
3018           8.485281      7.000000     7.0
706            8.082904     12.666667    14.0
7250           8.082904     12.333333    17.0
6766           7.847505      8.250000     8.0
5374           7.778175     12.500000    12.5
6393           7.071068      6.000000     6.0
820            7.071068      6.000000     6.0
995            7.071068      8.000000     8.0
518            7.071068     12.000000    12.0
2659           7.071068      7.000000     7.0
2887           6.928203     10.000000    14.0
3811           6.928203     12.000000    16.0
7428           6.833740      9.500000     8.0
2516           6.658328      9.333333     6.0
420            6.640204      8.600000    10.5
2337           6.615638      8.166667     5.0
3377           6.506407      7.333333     7.0
3856           6.454972     14.500000    17.0
202            6.396614      8.250000     6.5
2935           6.363961      8.500000     8.5
613            6.257440     10.400000     9.0
891            6.244998      9.000000    11.0
6780           6.219632      9.058824    10.0
6618           6.130525      8.250000     7.5
1950           6.114695     11.208333    10.0
...                 ...           ...     ...
2889                NaN     15.000000    15.0
6826                NaN     14.000000    14.0
5898                NaN      2.000000     2.0
4023                NaN     17.000000    17.0
5101                NaN      6.000000     6.0
3012                NaN      8.000000     8.0
7154                NaN     12.000000    12.0
4837                NaN     13.000000    13.0
281                 NaN      9.000000     9.0
835                 NaN     11.000000    11.0
788                 NaN     15.000000    15.0
398                 NaN     11.000000    11.0
6460                NaN     18.000000    18.0
6203                NaN     12.000000    12.0
4064                NaN     11.000000    11.0
2213                NaN     11.000000    11.0
1819                NaN     13.000000    13.0
1523                NaN      4.000000     4.0
3212                NaN     13.000000    13.0
5491                NaN     18.000000    18.0
1431                NaN     14.000000    14.0
4779                NaN     13.000000    13.0
6270                NaN     12.000000    12.0
3788                NaN     11.000000    11.0
5290                NaN     15.000000    15.0
1214                NaN     14.000000    14.0
7131                NaN     17.000000    17.0
4869                NaN     14.000000    14.0
340                 NaN     16.000000    16.0
3045                NaN     16.000000    16.0

[7485 rows x 3 columns]

# Part 2: Sentiment analysis
(1) Generating features

In [ ]:
df.approxQuantile("x", [0.5], 0.25)

In [55]:
data.groupBy('beer_name').agg({'overall': approxQuantile('overall', [0.5], 0.25)}).show(5)

NameError: name 'approxQuantile' is not defined

(2) Stochastic gradient descent

# Part 3: Scores versus text

# Part 4 (Competition): build your own linear classifier

In [7]:
spark.stop()